-- SHOW TIMEZONE
SELECT now();

create table timeZ (ts TIMESTAMP without time zone , tsz TIMESTAMP with time zone );

INSERT into timez VALUES('2024-01-12 10:45:00', '2024-01-12 10:45:00');

SELECT * FROM timeZ

SELECT CURRENT_DATE;
SELECT now()::DATE;
SELECT now()::TIME;
SELECT to_char(now(), 'YYYY/MM/DD');
SELECT CURRENT_DATE - INTERVAL '1 month 1 day';
SELECT age(CURRENT_DATE,'2003-09-27');
SELECT EXTRACT(YEAR FROM CURRENT_DATE);
SELECT EXTRACT(MONTH FROM  '2025-05-23'::DATE);